### ISSUE TITLE
failing on catkin_tools 0.4.x

### ISSUE THREAD

**Issue by k-okada** [jsk-ros-pkg/geneus#47]
```
Scanning dependencies of target nodelet_generate_messages_eus
Scanning dependencies of target pcl_msgs_generate_messages_eus
Scanning dependencies of target bond_generate_messages_eus
Scanning dependencies of target dynamic_tf_publisher_generate_messages_eus
Scanning dependencies of target jsk_recognition_msgs_generate_messages_eus
Scanning dependencies of target posedetection_msgs_generate_messages_eus
[  0%] [  1%] [  1%] [  1%] [  1%] [  1%] Generating EusLisp code from baxter_maintenance_msgs/CalibrateArmData.msg
Generating EusLisp code from baxter_maintenance_msgs/CalibrateArmEnable.msg
Generating EusLisp code from baxter_maintenance_msgs/TareEnable.msg
[  1%] Generating EusLisp code from baxter_maintenance_msgs/CalibrateArmData.msg
[  2%] Generating EusLisp code from baxter_maintenance_msgs/TareData.msg
[  2%] Generating EusLisp code from baxter_maintenance_msgs/CalibrateArmData.msg
Generating EusLisp code from baxter_maintenance_msgs/CalibrateArmData.msg
Generating EusLisp code from baxter_maintenance_msgs/CalibrateArmData.msg
Generating EusLisp code from baxter_maintenance_msgs/CalibrateArmData.msg
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 749, in generate_msg_from_spec
    genmsg.msg_loader.load_depends(msg_context, spec, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 344, in load_depends
    return load_msg_depends(msg_context, spec, msg_search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 313, in load_msg_depends
    depspec = load_msg_by_type(msg_context, resolved_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 119, in load_msg_by_type
    file_path = get_msg_file(package_name, base_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 85, in get_msg_file
    (base_type, package, str(search_path[package])))
MsgNotFound: Cannot locate message [CalibrateArmData] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
ERROR:  Cannot locate message [CalibrateArmData] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 752, in generate_msg_from_spec
    msgs = msg_list(package, search_path, '.msg')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 739, in msg_list
    files.extend([f for f in os.listdir(d) if f.endswith(ext)])
OSError: [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
ERROR:  [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 749, in generate_msg_from_spec
    genmsg.msg_loader.load_depends(msg_context, spec, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 344, in load_depends
    return load_msg_depends(msg_context, spec, msg_search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 313, in load_msg_depends
    depspec = load_msg_by_type(msg_context, resolved_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 119, in load_msg_by_type
    file_path = get_msg_file(package_name, base_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 85, in get_msg_file
    (base_type, package, str(search_path[package])))
MsgNotFound: Cannot locate message [TareData] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
ERROR:  Cannot locate message [TareData] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/CalibrateArmEnable.l] Error 3
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/CalibrateArmData.l] Error 3
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/TareEnable.l] Error 3
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 752, in generate_msg_from_spec
    msgs = msg_list(package, search_path, '.msg')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 739, in msg_list
    files.extend([f for f in os.listdir(d) if f.endswith(ext)])
OSError: [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 752, in generate_msg_from_spec
    msgs = msg_list(package, search_path, '.msg')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 739, in msg_list
    files.extend([f for f in os.listdir(d) if f.endswith(ext)])
OSError: [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
[  2%] ERROR:  [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
ERROR:  [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/CalibrateArmData.l] Error 3
make[1]: *** [CMakeFiles/jsk_recognition_msgs_generate_messages_eus.dir/all] Error 2
make[1]: make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/CalibrateArmData.l] Error 3
make[2]: *** Waiting for unfinished jobs....
*** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 752, in generate_msg_from_spec
    msgs = msg_list(package, search_path, '.msg')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 739, in msg_list
    files.extend([f for f in os.listdir(d) if f.endswith(ext)])
OSError: [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
[  2%] [  3%] ERROR:  [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
Generating EusLisp code from baxter_maintenance_msgs/CalibrateArmEnable.msg
[  3%] Generating EusLisp code from baxter_maintenance_msgs/TareData.msg
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/CalibrateArmData.l] Error 3
make[2]: *** Waiting for unfinished jobs....
[  4%] Generating EusLisp code from baxter_maintenance_msgs/CalibrateArmEnable.msg
Generating EusLisp code from baxter_maintenance_msgs/TareEnable.msg
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 752, in generate_msg_from_spec
    msgs = msg_list(package, search_path, '.msg')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 739, in msg_list
    files.extend([f for f in os.listdir(d) if f.endswith(ext)])
OSError: [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
[  4%] ERROR:  [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
Generating EusLisp code from baxter_maintenance_msgs/CalibrateArmEnable.msg
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 752, in generate_msg_from_spec
    msgs = msg_list(package, search_path, '.msg')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 739, in msg_list
    files.extend([f for f in os.listdir(d) if f.endswith(ext)])
OSError: [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
ERROR:  [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/TareData.l] Error 3
make[1]: *** [CMakeFiles/nodelet_generate_messages_eus.dir/all] Error 2
Generating EusLisp code from baxter_maintenance_msgs/UpdateSource.msg
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/CalibrateArmData.l] Error 3
make[2]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 752, in generate_msg_from_spec
    msgs = msg_list(package, search_path, '.msg')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 739, in msg_list
    files.extend([f for f in os.listdir(d) if f.endswith(ext)])
OSError: [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
[  5%] ERROR:  [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/CalibrateArmData.l] Error 3
make[2]: *** Waiting for unfinished jobs....
[  6%] Generating EusLisp code from baxter_maintenance_msgs/UpdateSources.msg
Generating EusLisp code from baxter_maintenance_msgs/CalibrateArmEnable.msg
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 749, in generate_msg_from_spec
    genmsg.msg_loader.load_depends(msg_context, spec, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 344, in load_depends
    return load_msg_depends(msg_context, spec, msg_search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 313, in load_msg_depends
    depspec = load_msg_by_type(msg_context, resolved_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 119, in load_msg_by_type
    file_path = get_msg_file(package_name, base_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 85, in get_msg_file
    (base_type, package, str(search_path[package])))
MsgNotFound: Cannot locate message [CalibrateArmData] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
ERROR:  Cannot locate message [CalibrateArmData] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 749, in generate_msg_from_spec
    genmsg.msg_loader.load_depends(msg_context, spec, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 344, in load_depends
    return load_msg_depends(msg_context, spec, msg_search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 313, in load_msg_depends
    depspec = load_msg_by_type(msg_context, resolved_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 119, in load_msg_by_type
    file_path = get_msg_file(package_name, base_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 85, in get_msg_file
    (base_type, package, str(search_path[package])))
MsgNotFound: Cannot locate message [CalibrateArmData] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
ERROR:  Cannot locate message [CalibrateArmData] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 752, in generate_msg_from_spec
    msgs = msg_list(package, search_path, '.msg')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 739, in msg_list
    files.extend([f for f in os.listdir(d) if f.endswith(ext)])
OSError: [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
ERROR:  [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/CalibrateArmEnable.l] Error 3
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/CalibrateArmEnable.l] Error 3
make[1]: *** [CMakeFiles/bond_generate_messages_eus.dir/all] Error 2
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/TareData.l] Error 3
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 749, in generate_msg_from_spec
    genmsg.msg_loader.load_depends(msg_context, spec, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 344, in load_depends
    return load_msg_depends(msg_context, spec, msg_search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 313, in load_msg_depends
    depspec = load_msg_by_type(msg_context, resolved_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 119, in load_msg_by_type
    file_path = get_msg_file(package_name, base_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 85, in get_msg_file
    (base_type, package, str(search_path[package])))
MsgNotFound: Cannot locate message [CalibrateArmData] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
ERROR:  Cannot locate message [CalibrateArmData] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 749, in generate_msg_from_spec
    genmsg.msg_loader.load_depends(msg_context, spec, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 344, in load_depends
    return load_msg_depends(msg_context, spec, msg_search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 313, in load_msg_depends
    depspec = load_msg_by_type(msg_context, resolved_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 119, in load_msg_by_type
    file_path = get_msg_file(package_name, base_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 85, in get_msg_file
    (base_type, package, str(search_path[package])))
MsgNotFound: Cannot locate message [TareData] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
ERROR:  Cannot locate message [TareData] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/CalibrateArmEnable.l] Error 3
make[1]: *** [CMakeFiles/pcl_msgs_generate_messages_eus.dir/all] Error 2
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 752, in generate_msg_from_spec
    msgs = msg_list(package, search_path, '.msg')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 739, in msg_list
    files.extend([f for f in os.listdir(d) if f.endswith(ext)])
OSError: [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
ERROR:  [Errno 2] No such file or directory: '/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg'
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/TareEnable.l] Error 3
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/UpdateSource.l] Error 3
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 749, in generate_msg_from_spec
    genmsg.msg_loader.load_depends(msg_context, spec, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 344, in load_depends
    return load_msg_depends(msg_context, spec, msg_search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 313, in load_msg_depends
    depspec = load_msg_by_type(msg_context, resolved_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 119, in load_msg_by_type
    file_path = get_msg_file(package_name, base_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 85, in get_msg_file
    (base_type, package, str(search_path[package])))
MsgNotFound: Cannot locate message [UpdateSource] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
ERROR:  Cannot locate message [UpdateSource] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/geneus_main.py", line 168, in genmain
    retcode = generate_msg(options.package, args[1:], options.outdir, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 721, in generate_msg
    generate_msg_from_spec(msg_context, spec, search_path, out_dir, pkg)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/geneus/generate.py", line 749, in generate_msg_from_spec
    genmsg.msg_loader.load_depends(msg_context, spec, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 344, in load_depends
    return load_msg_depends(msg_context, spec, msg_search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 313, in load_msg_depends
    depspec = load_msg_by_type(msg_context, resolved_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 119, in load_msg_by_type
    file_path = get_msg_file(package_name, base_type, search_path)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/genmsg/msg_loader.py", line 85, in get_msg_file
    (base_type, package, str(search_path[package])))
MsgNotFound: Cannot locate message [CalibrateArmData] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
ERROR:  Cannot locate message [CalibrateArmData] in package [baxter_maintenance_msgs] with paths [['/home/wkentaro/ros/test_geneus/devel/.private/baxter_maintenance_msgs/share/baxter_maintenance_msgs/msg']]
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/UpdateSources.l] Error 3
make[1]: *** [CMakeFiles/posedetection_msgs_generate_messages_eus.dir/all] Error 2
make[2]: *** [/home/wkentaro/ros/test_geneus/devel/.private/jsk_baxter_startup/share/roseus/ros/baxter_maintenance_msgs/msg/CalibrateArmEnable.l] Error 3
make[1]: *** [CMakeFiles/dynamic_tf_publisher_generate_messages_eus.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by k-okada** [comment]
solved via https://github.com/jsk-ros-pkg/jsk_roseus/pull/447
